### ISSUE TITLE
2D version

### ISSUE THREAD

**Issue by Yuanzizizi** [ZJU-FAST-Lab/Implicit-SDF-Planner#10]
Hi!
Have the 2D version and shape variant demos been released?

**Comment by Pupillen** [comment]
Hi, the code for the 2D version will be open sourced under this repository: [Implicit-SVSDF-Planner](https://github.com/ZJU-FAST-Lab/Implicit-SVSDF-Planner) which we've been organizing recently!

**Comment by Yuanzizizi** [comment]
That's great news! Would it be possible to know approximately when it will be released?

**Comment by Pupillen** [comment]
About this week.
