### ISSUE TITLE
build.sh Catkin_make Error

### ISSUE THREAD

**Issue by StudtTJX** [ZJU-FAST-Lab/Implicit-SDF-Planner#3]
Hello~ I meet an error when catkin_make. May I ask if you have time to provide assistance？Thanks!
![image](https://github.com/ZJU-FAST-Lab/Implicit-SDF-Planner/assets/97785421/b91ee7c2-600c-4f9a-be06-941958cabf07)

**Comment by Pupillen** [comment]
It seems that the Libigl libraries are not linked. What is your OS? Make sure you link the libraries in the lib folder. Alternatively, you can manually compile Libigl to create a static library and link it (https://libigl.github.io/static-library/). Note you will also need to add the "-fPIC" compile option in CMakeLists if you choose to create a static library.

**Comment by StudtTJX** [comment]
> It seems that the Libigl libraries are not linked. What is your OS? Make sure you link the libraries in the lib folder. Alternatively, you can manually compile Libigl to create a static library and link it (https://libigl.github.io/static-library/). Note you will also need to add the "-fPIC" compile option in CMakeLists if you choose to create a static library.

Thanks a lot! I've solved my issue.
