### ISSUE TITLE
关于地图

### ISSUE THREAD

**Issue by perchon** [ZJU-FAST-Lab/Implicit-SDF-Planner#5]
您好，我想试一下在不同地图环境下的实验效果，请问如何更改地图呢？

**Comment by Pupillen** [comment]
可以修改launch文件当中的map_id或者https://github.com/ZJU-FAST-Lab/Implicit-SDF-Planner/blob/main/src/map_manager/src/globalmap_gene.cpp中修改地图

**Comment by perchon** [comment]
好的，明白了，想问以下globalmap.cpp中关于地图的代码是可以通过unity导出的吗？
