### ISSUE TITLE
关于自定义shape

### ISSUE THREAD

**Issue by perchon** [ZJU-FAST-Lab/Implicit-SDF-Planner#6]
你好，我通过solidworks导出了obj格式的自定义shape并命名为sim.obj，并且将obj文件导入了Implicit-SDF-Planner-main/src/plan_manager/shapes目录下，在config的yaml文件下更换默认的obj为sim.obj，但是运行并没有出现我自己的shape，请问可以指导一下吗？还应该在哪些文件下作出改动啊？

**Comment by Pupillen** [comment]
对应launch文件需要与yaml配套，感觉没有修改yaml文件，另外自定义形状的话强烈建议使用meshlab把顶点，边简化，尽可能简单的几何体使用libigl计算的话效率会高一些，类似这里举例的L形状
