### ISSUE TITLE
碰撞信息反馈

### ISSUE THREAD

**Issue by Flipped0** [ZJU-FAST-Lab/Implicit-SDF-Planner#7]
您好，请问如果希望在发生碰撞时反馈发生碰撞的坐标和相关信息，应该如何调整代码呢？谢谢！

**Comment by Pupillen** [comment]
addSaftyPenaOnSweptVolumeParallel函数中有getSDFofSweptVolume是所有障碍物点对扫掠体积的SDF数值，大于0即发生碰撞。对应的障碍物点坐标是pos_eva。

**Comment by Flipped0** [comment]
谢谢！


------------------ 原始邮件 ------------------
发件人: Tingrui Zhang ***@***.***&gt;
发送时间: 2023年12月21日 19:51
收件人: ZJU-FAST-Lab/Implicit-SDF-Planner ***@***.***&gt;
抄送: Flipped0 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ZJU-FAST-Lab/Implicit-SDF-Planner] 碰撞信息反馈 (Issue #7)





 
addSaftyPenaOnSweptVolumeParallel函数中有getSDFofSweptVolume是所有障碍物点对扫掠体积的SDF数值，大于0即发生碰撞。对应的障碍物点坐标是pos_eva。
