### ISSUE TITLE
2D version and shape variant demos

### ISSUE THREAD

**Issue by yangxi-shi** [ZJU-FAST-Lab/Implicit-SDF-Planner#8]
Hi！
Wondering when can we get access to the 2D version and shape variant demos?
Interested in that because we plan to use the algorithm on multi-agent any-shape formation control
Thanks!

**Comment by Pupillen** [comment]
Thank you for your interest in our work, the latest enhancements to our papers (including 2D) are currently under review and the results will be available by the end of the month, if the paper is accepted we will open source it in April!

**Comment by yangxi-shi** [comment]
Thanks for your information.

**Comment by Yuanzizizi** [comment]
"May I ask if the demos for the 2D version and shape variants have been released?
